/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softech.project;

import com.softech.project.dao.DaoHoadonnhap;

import com.softech.project.model.ModelLogin;

import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Menu extends javax.swing.JFrame {
    private DefaultTableModel tblModel;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);// center form in the screen  
        initTable();
        loadDataToMenu();
    }
 private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Name", "SL", "Gia"});
        tblHoadonchtiec.setModel(tblModel);

    }
 private void loadDataToMenu() {
        try {
            DaoHoadonnhap daoQl_Menu = new DaoHoadonnhap();

            List<ModelLogin> list = daoQl_Menu.findAll1(); 
            tblModel.setRowCount(0);
            for (ModelLogin it : list) {
                tblModel.addRow(new Object[]{
                    it.getName(), it.getSl(), it.getGia()
                });

            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rdbCafeDen = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rdbCafeSua = new javax.swing.JRadioButton();
        rdbCafeTrung = new javax.swing.JRadioButton();
        rdbCafeXay = new javax.swing.JRadioButton();
        rdbCafeSuaSG = new javax.swing.JRadioButton();
        rdbCafeDenSG = new javax.swing.JRadioButton();
        rdbThapCamEp = new javax.swing.JRadioButton();
        rdbOiep = new javax.swing.JRadioButton();
        rdbCamVat = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        rdbThomEp = new javax.swing.JRadioButton();
        rdbCaChuaEp = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdbCaRoEp = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        rdbSinhToTac = new javax.swing.JRadioButton();
        rdbSinhToDua = new javax.swing.JRadioButton();
        rdbSinhToThom = new javax.swing.JRadioButton();
        rdbSinhToCaRot = new javax.swing.JRadioButton();
        rdbSinhToCaChua = new javax.swing.JRadioButton();
        rdbSinhToThapCam = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        rdbSuaChuaCam = new javax.swing.JRadioButton();
        rdbSuaChuaDua = new javax.swing.JRadioButton();
        rdbSuaChuaNho = new javax.swing.JRadioButton();
        rdbSuaChuaDauTay = new javax.swing.JRadioButton();
        rdbSuaChuaTraXanh = new javax.swing.JRadioButton();
        rdbSuaChuaChanhLeo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoadonchtiec = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        bntPlus = new javax.swing.JButton();
        txtTienNhan = new javax.swing.JTextField();
        rdbSizeM = new javax.swing.JRadioButton();
        rdbSizeL = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTienThoi = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSl = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btnHoadon = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        rdbNuocNgot = new javax.swing.JRadioButton();
        rdbHatHuongDuongDua = new javax.swing.JRadioButton();
        rdbHatHuongDuong = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        cbxVoucher = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(84, 39, 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(84, 39, 7));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/cafe-latte.jpg"))); // NOI18N

        buttonGroup1.add(rdbCafeDen);
        rdbCafeDen.setText("Cafe Đen");
        rdbCafeDen.setActionCommand("3");

        jLabel2.setFont(new java.awt.Font("VNI-Ariston", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Coffee");

        buttonGroup1.add(rdbCafeSua);
        rdbCafeSua.setText("Cafe Sữa");
        rdbCafeSua.setActionCommand("5");

        buttonGroup1.add(rdbCafeTrung);
        rdbCafeTrung.setText("Cafe Trứng");
        rdbCafeTrung.setActionCommand("7");

        buttonGroup1.add(rdbCafeXay);
        rdbCafeXay.setText("Cafe Xay Chocolate");
        rdbCafeXay.setActionCommand("8");

        buttonGroup1.add(rdbCafeSuaSG);
        rdbCafeSuaSG.setText("Cafe Sữa Sài Gòn");
        rdbCafeSuaSG.setActionCommand("6");

        buttonGroup1.add(rdbCafeDenSG);
        rdbCafeDenSG.setText("Cafe Đen Sài Gòn");
        rdbCafeDenSG.setActionCommand("4");

        buttonGroup1.add(rdbThapCamEp);
        rdbThapCamEp.setText("Nước Ép Thập Cẩm");
        rdbThapCamEp.setActionCommand("12");

        buttonGroup1.add(rdbOiep);
        rdbOiep.setText("ổi Ép");
        rdbOiep.setActionCommand("14");

        buttonGroup1.add(rdbCamVat);
        rdbCamVat.setText("Cam Vắt");
        rdbCamVat.setActionCommand("9");

        jLabel3.setFont(new java.awt.Font("VNI-Ariston", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Friut Juice");

        buttonGroup1.add(rdbThomEp);
        rdbThomEp.setText("Thơm Ép");

        buttonGroup1.add(rdbCaChuaEp);
        rdbCaChuaEp.setText("Cà Chua Ép");
        rdbCaChuaEp.setActionCommand("1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/Friut Juice.jpg"))); // NOI18N

        buttonGroup1.add(rdbCaRoEp);
        rdbCaRoEp.setText("Cà Rốt Ép");
        rdbCaRoEp.setActionCommand("2");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/smoothies.jpg"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("VNI-Ariston", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Friut Juice");

        buttonGroup1.add(rdbSinhToTac);
        rdbSinhToTac.setText("SInh Tố Tắc");
        rdbSinhToTac.setActionCommand("18");

        buttonGroup1.add(rdbSinhToDua);
        rdbSinhToDua.setText("SInh Tố Dừa");
        rdbSinhToDua.setActionCommand("17");

        buttonGroup1.add(rdbSinhToThom);
        rdbSinhToThom.setText("SInh Tố Thơm");
        rdbSinhToThom.setActionCommand("20");

        buttonGroup1.add(rdbSinhToCaRot);
        rdbSinhToCaRot.setText("SInh Tố Cà Rốt ");
        rdbSinhToCaRot.setToolTipText("");
        rdbSinhToCaRot.setActionCommand("16");

        buttonGroup1.add(rdbSinhToCaChua);
        rdbSinhToCaChua.setText("SInh Tố Cà Chua");
        rdbSinhToCaChua.setActionCommand("15");

        buttonGroup1.add(rdbSinhToThapCam);
        rdbSinhToThapCam.setText("SInh Tố Thập Cẩm");
        rdbSinhToThapCam.setActionCommand("19");

        jLabel12.setFont(new java.awt.Font("VNI-Ariston", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Yogurt");

        buttonGroup1.add(rdbSuaChuaCam);
        rdbSuaChuaCam.setText("Sữa Chua Cam");
        rdbSuaChuaCam.setActionCommand("21");

        buttonGroup1.add(rdbSuaChuaDua);
        rdbSuaChuaDua.setText("Sữa Chua Dừa");
        rdbSuaChuaDua.setActionCommand("24");

        buttonGroup1.add(rdbSuaChuaNho);
        rdbSuaChuaNho.setText("Sữa Chua Nho");
        rdbSuaChuaNho.setActionCommand("25");

        buttonGroup1.add(rdbSuaChuaDauTay);
        rdbSuaChuaDauTay.setText("Sữa Chua Dâu Tây");
        rdbSuaChuaDauTay.setActionCommand("23");

        buttonGroup1.add(rdbSuaChuaTraXanh);
        rdbSuaChuaTraXanh.setText("Sữa Chua Trà Xanh");
        rdbSuaChuaTraXanh.setToolTipText("");
        rdbSuaChuaTraXanh.setActionCommand("26");

        buttonGroup1.add(rdbSuaChuaChanhLeo);
        rdbSuaChuaChanhLeo.setText("Sữa Chua Chanh leo");
        rdbSuaChuaChanhLeo.setActionCommand("22");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/yogurt.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rdbCafeSua)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel2))
                                    .addComponent(rdbCafeDen)
                                    .addComponent(rdbCafeXay)
                                    .addComponent(rdbCafeSuaSG)
                                    .addComponent(rdbCafeDenSG))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbCamVat)
                                            .addComponent(rdbThomEp)
                                            .addComponent(rdbThapCamEp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rdbOiep)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdbCaChuaEp)
                                            .addComponent(rdbCaRoEp)))))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbCafeTrung))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbSinhToThapCam)
                                    .addComponent(rdbSinhToCaChua)
                                    .addComponent(rdbSinhToCaRot)
                                    .addComponent(rdbSinhToThom)
                                    .addComponent(rdbSinhToDua)
                                    .addComponent(rdbSinhToTac)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbSuaChuaDua)
                                    .addComponent(rdbSuaChuaDauTay)
                                    .addComponent(rdbSuaChuaTraXanh)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rdbSuaChuaCam)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdbSuaChuaNho)
                                    .addComponent(rdbSuaChuaChanhLeo)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel12))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbSuaChuaCam, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbSuaChuaDua))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel10)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdbSuaChuaNho))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbSinhToTac)
                                    .addComponent(rdbSuaChuaDauTay))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbSinhToDua)
                                    .addComponent(rdbSuaChuaTraXanh))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbSinhToThom)
                                    .addComponent(rdbSuaChuaChanhLeo)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rdbThomEp)
                                .addGap(18, 18, 18)
                                .addComponent(rdbCaRoEp)
                                .addGap(18, 18, 18)
                                .addComponent(rdbCaChuaEp)
                                .addGap(18, 18, 18)
                                .addComponent(rdbThapCamEp)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdbSinhToCaRot)
                                .addGap(18, 18, 18)
                                .addComponent(rdbSinhToCaChua)
                                .addGap(18, 18, 18)
                                .addComponent(rdbSinhToThapCam))
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdbOiep, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbCamVat))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbCafeDen)
                        .addGap(13, 13, 13)
                        .addComponent(rdbCafeSua)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCafeTrung)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCafeDenSG)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCafeSuaSG)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCafeXay)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        tblHoadonchtiec.setBackground(new java.awt.Color(84, 39, 7));
        tblHoadonchtiec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblHoadonchtiec.setForeground(new java.awt.Color(255, 255, 255));
        tblHoadonchtiec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblHoadonchtiec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoadonchtiecMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoadonchtiec);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 360, 430));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Số lượng:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, -1, -1));

        bntPlus.setBackground(new java.awt.Color(204, 51, 0));
        bntPlus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bntPlus.setText("+");
        jPanel1.add(bntPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, -1, 26));

        txtTienNhan.setBackground(new java.awt.Color(139, 69, 19));
        txtTienNhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtTienNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 550, 220, 26));

        rdbSizeM.setBackground(new java.awt.Color(84, 39, 7));
        buttonGroup2.add(rdbSizeM);
        rdbSizeM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdbSizeM.setForeground(new java.awt.Color(255, 255, 255));
        rdbSizeM.setText("Size M");
        rdbSizeM.setActionCommand("sizeM");
        rdbSizeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSizeMActionPerformed(evt);
            }
        });
        jPanel1.add(rdbSizeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, -1, -1));

        rdbSizeL.setBackground(new java.awt.Color(84, 39, 7));
        buttonGroup2.add(rdbSizeL);
        rdbSizeL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdbSizeL.setForeground(new java.awt.Color(255, 255, 255));
        rdbSizeL.setText("Size L");
        rdbSizeL.setActionCommand("sizeL");
        jPanel1.add(rdbSizeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/printer.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 660, 76, 77));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/logo-1in.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 610, 110, 160));

        txtTienThoi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTienThoi.setForeground(new java.awt.Color(255, 255, 255));
        txtTienThoi.setText("0 VNĐ");
        jPanel1.add(txtTienThoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Size:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("  Tổng thối:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 140, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("  Tổng tiền:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 460, -1, -1));

        txtSl.setBackground(new java.awt.Color(139, 69, 19));
        txtSl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtSl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 49, 26));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Voucher:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 500, 110, -1));

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(255, 255, 255));
        lblTongTien.setText("0 VNĐ");
        jPanel1.add(lblTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, -1, -1));

        btnthem.setBackground(new java.awt.Color(204, 51, 0));
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/add (2).png"))); // NOI18N
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel1.add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 76, 77));

        btnHoadon.setBackground(new java.awt.Color(204, 51, 0));
        btnHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/bill.png"))); // NOI18N
        jPanel1.add(btnHoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 660, 76, 77));

        jPanel3.setBackground(new java.awt.Color(84, 39, 7));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("VNI-Ariston", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Beverage and Snacks");

        buttonGroup1.add(rdbNuocNgot);
        rdbNuocNgot.setText("Nước Ngọt");
        rdbNuocNgot.setActionCommand("13");

        buttonGroup1.add(rdbHatHuongDuongDua);
        rdbHatHuongDuongDua.setText("Hạt Hướng Dương Dừa");
        rdbHatHuongDuongDua.setActionCommand("11");

        buttonGroup1.add(rdbHatHuongDuong);
        rdbHatHuongDuong.setText("Hạt Hướng Dương");
        rdbHatHuongDuong.setActionCommand("10");

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("jRadioButton4");

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("jRadioButton4");

        buttonGroup1.add(jRadioButton20);
        jRadioButton20.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setText("jRadioButton4");

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton21.setText("jRadioButton4");

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton22.setText("jRadioButton4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton22))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdbHatHuongDuongDua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton21))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdbHatHuongDuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton20))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdbNuocNgot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton18)))
                        .addGap(171, 171, 171))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbNuocNgot)
                    .addComponent(jRadioButton18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHatHuongDuong)
                    .addComponent(jRadioButton20))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHatHuongDuongDua)
                    .addComponent(jRadioButton21))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 570, 260));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tổng nhận:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 140, -1));

        cbxVoucher.setBackground(new java.awt.Color(139, 69, 19));
        cbxVoucher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxVoucher.setForeground(new java.awt.Color(255, 255, 255));
        cbxVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 500, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        MainUser mu= new MainUser();

        mu.setVisible(true);
        mu.pack();
        mu.setLocationRelativeTo(null);
        mu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
           
    }//GEN-LAST:event_btnthemActionPerformed

    private void rdbSizeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSizeMActionPerformed
        String cmd = evt.getActionCommand();
           
           
    }//GEN-LAST:event_rdbSizeMActionPerformed

    private void tblHoadonchtiecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoadonchtiecMouseClicked
        try {
            int row = tblHoadonchtiec.getSelectedRow();
            if (row >= 0) {
                String drinkandfood = (String) tblHoadonchtiec.getValueAt(row, 0);
                DaoHoadonnhap daoQl_Menu = new DaoHoadonnhap();
                ModelLogin mdl = daoQl_Menu.findName(drinkandfood);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tblHoadonchtiecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPlus;
    private javax.swing.JButton btnHoadon;
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxVoucher;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JRadioButton rdbCaChuaEp;
    private javax.swing.JRadioButton rdbCaRoEp;
    private javax.swing.JRadioButton rdbCafeDen;
    private javax.swing.JRadioButton rdbCafeDenSG;
    private javax.swing.JRadioButton rdbCafeSua;
    private javax.swing.JRadioButton rdbCafeSuaSG;
    private javax.swing.JRadioButton rdbCafeTrung;
    private javax.swing.JRadioButton rdbCafeXay;
    private javax.swing.JRadioButton rdbCamVat;
    private javax.swing.JRadioButton rdbHatHuongDuong;
    private javax.swing.JRadioButton rdbHatHuongDuongDua;
    private javax.swing.JRadioButton rdbNuocNgot;
    private javax.swing.JRadioButton rdbOiep;
    private javax.swing.JRadioButton rdbSinhToCaChua;
    private javax.swing.JRadioButton rdbSinhToCaRot;
    private javax.swing.JRadioButton rdbSinhToDua;
    private javax.swing.JRadioButton rdbSinhToTac;
    private javax.swing.JRadioButton rdbSinhToThapCam;
    private javax.swing.JRadioButton rdbSinhToThom;
    private javax.swing.JRadioButton rdbSizeL;
    private javax.swing.JRadioButton rdbSizeM;
    private javax.swing.JRadioButton rdbSuaChuaCam;
    private javax.swing.JRadioButton rdbSuaChuaChanhLeo;
    private javax.swing.JRadioButton rdbSuaChuaDauTay;
    private javax.swing.JRadioButton rdbSuaChuaDua;
    private javax.swing.JRadioButton rdbSuaChuaNho;
    private javax.swing.JRadioButton rdbSuaChuaTraXanh;
    private javax.swing.JRadioButton rdbThapCamEp;
    private javax.swing.JRadioButton rdbThomEp;
    private javax.swing.JTable tblHoadonchtiec;
    private javax.swing.JTextField txtSl;
    private javax.swing.JTextField txtTienNhan;
    private javax.swing.JLabel txtTienThoi;
    // End of variables declaration//GEN-END:variables
}
