/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softech.project;

import com.softech.project.dao.DaoQl_Menu;
import com.softech.project.helper.ImageHelper;
import com.softech.project.model.ModelLogin;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QL_menu extends javax.swing.JFrame {

    private DefaultTableModel tblModel;
    private QL_menu parentl;
    private byte[] personalImage;

    /**
     * Creates new form QL_menu
     */
    public QL_menu() {
        initComponents();
        this.setLocationRelativeTo(null);// center form in the screen    

        initTable();
        loadDataToMenu();
    }

    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Drink and Food", "size M", "size L", "image"});
        tblMenu.setModel(tblModel);

    }

    private void loadDataToMenu() {
        try {
            DaoQl_Menu daoQl_Menu = new DaoQl_Menu();

            List<ModelLogin> list = daoQl_Menu.findAll();
            tblModel.setRowCount(0);
            for (ModelLogin it : list) {
                tblModel.addRow(new Object[]{
                    it.getDrinkAndFood(), it.getSizeM(), it.getSizeL(), it.getImage()
                });

            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtDrinkandFood = new javax.swing.JTextField();
        txtSizeL = new javax.swing.JTextField();
        txtSizeM = new javax.swing.JTextField();
        lblIamge = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnAddImg = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnTaoMoi = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(84, 39, 7));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản Lý Menu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Drink and Food:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("size M:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Size L:");

        txtDrinkandFood.setBackground(new java.awt.Color(139, 69, 19));
        txtDrinkandFood.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDrinkandFood.setForeground(new java.awt.Color(255, 255, 255));
        txtDrinkandFood.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDrinkandFood.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtSizeL.setBackground(new java.awt.Color(139, 69, 19));
        txtSizeL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSizeL.setForeground(new java.awt.Color(255, 255, 255));
        txtSizeL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSizeL.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtSizeM.setBackground(new java.awt.Color(139, 69, 19));
        txtSizeM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSizeM.setForeground(new java.awt.Color(255, 255, 255));
        txtSizeM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSizeM.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        lblIamge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/soda (1).png"))); // NOI18N
        lblIamge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(105, 49, 10), new java.awt.Color(105, 49, 10), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        tblMenu.setAutoCreateRowSorter(true);
        tblMenu.setBackground(new java.awt.Color(139, 69, 19));
        tblMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblMenu.setForeground(new java.awt.Color(255, 255, 255));
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMenu.setGridColor(new java.awt.Color(0, 0, 0));
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        btnAddImg.setBackground(new java.awt.Color(139, 69, 19));
        btnAddImg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddImg.setForeground(new java.awt.Color(255, 255, 255));
        btnAddImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/open-file-icon-16.png"))); // NOI18N
        btnAddImg.setText("Add Img");
        btnAddImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAddImg.setHideActionText(true);
        btnAddImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddImg.setSelected(true);
        btnAddImg.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAddImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImgActionPerformed(evt);
            }
        });

        btnTaoMoi.setBackground(new java.awt.Color(139, 69, 19));
        btnTaoMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTaoMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/new-icon-16.png"))); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTaoMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaoMoiMouseClicked(evt);
            }
        });

        btnCapNhap.setBackground(new java.awt.Color(139, 69, 19));
        btnCapNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/Actions-document-edit-icon-16.png"))); // NOI18N
        btnCapNhap.setText("Cập Nhập");
        btnCapNhap.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCapNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapNhapMouseClicked(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(139, 69, 19));
        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/Save-icon.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(139, 69, 19));
        btnxoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(255, 255, 255));
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnxoa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnxoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnxoaMouseClicked(evt);
            }
        });

        btnhome.setBackground(new java.awt.Color(139, 69, 19));
        btnhome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/home.png"))); // NOI18N
        btnhome.setText("Home");
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnhome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(245, 245, 245))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSizeM, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDrinkandFood, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSizeL, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIamge, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddImg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnTaoMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDrinkandFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSizeM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSizeL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIamge, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddImg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoMoi)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhap)
                    .addComponent(btnxoa)
                    .addComponent(btnhome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoMoiMouseClicked
        txtDrinkandFood.setText("");
        txtSizeM.setText("");
        txtSizeL.setText("");
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/soda (1).png"));
        lblIamge.setIcon(icon);
    }//GEN-LAST:event_btnTaoMoiMouseClicked

    private void btnCapNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhapMouseClicked

        if (txtDrinkandFood.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Drink and Food ko duoc de trong");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Bán có muốn cập nhập lại không ?") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            ModelLogin mdl = new ModelLogin();
            mdl.setDrinkAndFood(txtDrinkandFood.getText());
            mdl.setSizeM(Integer.parseInt(txtSizeM.getText()));
            mdl.setSizeL(Integer.parseInt(txtSizeL.getText()));
            mdl.setImage(personalImage);

            DaoQl_Menu daoQ = new DaoQl_Menu();
            if (daoQ.update(mdl)) {
                JOptionPane.showMessageDialog(this, "Drink and Food đã được cập nhập");
                loadDataToMenu();
            } else {
                JOptionPane.showMessageDialog(this, "Drink and Food chưa cập nhập");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnCapNhapMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked

        if (txtDrinkandFood.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Drink and Food ko duoc de trong");
            return;
        }

        try {
            ModelLogin mdl = new ModelLogin();
            mdl.setDrinkAndFood(txtDrinkandFood.getText());
            mdl.setSizeM(Integer.parseInt(txtSizeM.getText()));
            mdl.setSizeL(Integer.parseInt(txtSizeL.getText()));
            mdl.setImage(personalImage);

            DaoQl_Menu daoQ = new DaoQl_Menu();
            if (daoQ.insert(mdl)) {
                JOptionPane.showMessageDialog(this, "Drink and Food đã được lưu");
                loadDataToMenu();
            } else {
                JOptionPane.showMessageDialog(this, "Drink and Food chưa được lưu");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
        txtDrinkandFood.setText("");
        txtSizeM.setText("");
        txtSizeL.setText("");
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/soda (1).png"));
        lblIamge.setIcon(icon);
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnxoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxoaMouseClicked
        if (txtDrinkandFood.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Drink and Food ko duoc de trong");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Bán có muốn xóa không ?") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            DaoQl_Menu daoQ = new DaoQl_Menu();
            if (daoQ.delete(txtDrinkandFood.getText())) {
                JOptionPane.showMessageDialog(this, "Drink and Food đã được Xóa");
                loadDataToMenu();
            } else {
                JOptionPane.showMessageDialog(this, "Drink and Food chưa Xóa");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
        txtDrinkandFood.setText("");
        txtSizeM.setText("");
        txtSizeL.setText("");
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/soda (1).png"));
        lblIamge.setIcon(icon);
    }//GEN-LAST:event_btnxoaMouseClicked

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        try {
            int row = tblMenu.getSelectedRow();
            if (row >= 0) {
                String drinkandfood = (String) tblMenu.getValueAt(row, 0);
                DaoQl_Menu daoQl_Menu = new DaoQl_Menu();
                ModelLogin mdl = daoQl_Menu.findDrinkAndFood(drinkandfood);

                if (mdl != null) {

                    txtDrinkandFood.setText(mdl.getDrinkAndFood());
                    txtSizeM.setText(String.valueOf(mdl.getSizeM()));
                    txtSizeL.setText(String.valueOf(mdl.getSizeL()));
                    if (mdl.getImage() != null) {
                        Image img = ImageHelper.createImageFromByteArray(mdl.getImage(), "jpg");
                        lblIamge.setIcon(new ImageIcon(img));
                        personalImage = mdl.getImage();

                    } else {
                        personalImage = mdl.getImage();
                        ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/project/IconAndImg/soda (1).png"));
                        lblIamge.setIcon(icon);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tblMenuMouseClicked

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
        MainAdmin ma = new MainAdmin();

        ma.setVisible(true);
        ma.pack();
        ma.setLocationRelativeTo(null);
        ma.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btnAddImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImgActionPerformed
       JFileChooser chooser = new JFileChooser();
       chooser.setFileFilter(new FileFilter() {
           @Override
           public boolean accept(File f) {
               if (f.isDirectory()) {
                   return true;
               } else {
                   return f.getName().toLowerCase().endsWith(".jpg");
               }
           }

           @Override
           public String getDescription() {
               return "Image File (*.jpg)";
           }
       });
        if (chooser.showOpenDialog(parentl)== JFileChooser.CANCEL_OPTION) {
            return;
        }
        
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = ImageHelper.resize(icon.getImage(), 141, 141);
            ImageIcon resizeIcon = new ImageIcon(img);
            lblIamge.setIcon(resizeIcon);
            personalImage = ImageHelper.toByteArray(img, "jpg");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnAddImgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddImg;
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIamge;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtDrinkandFood;
    private javax.swing.JTextField txtSizeL;
    private javax.swing.JTextField txtSizeM;
    // End of variables declaration//GEN-END:variables
}
